### ISSUE TITLE
Heroku error

### ISSUE THREAD

**Issue by epicfaace** [ecosyste-ms/digest#15]
1. Go to https://digest.ecosyste.ms/
2. Type in "https://registry.npmjs.org/playwright/"
3. Page goes to https://digest.ecosyste.ms/digest?url=https%3A%2F%2Fregistry.npmjs.org%2Fplaywright%2F and shows a Heroku error

<img width="1202" alt="image" src="https://user-images.githubusercontent.com/1689183/167916082-9a7f22bf-4cae-4d3c-b8aa-e87cbaab3be0.png">

**Comment by andrew** [comment]
Looks like it's timed out but the error isn't properly handled so it crashed the app!

**Comment by andrew** [comment]
```
2022-05-12T09:08:51.214961+00:00 heroku[web.1]: State changed from starting to up
2022-05-12T09:09:22.876137+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/digest?url=https%3A%2F%2Fregistry.npmjs.org%2Fplaywright%2F" host=digest.ecosyste.ms request_id=8e986288-2dad-447e-b93d-5288e568c78d fwd="213.225.225.72,172.70.85.21" dyno=web.1 connect=0ms service=30000ms status=503 bytes=0 protocol=http
2022-05-12T09:09:22.881314+00:00 app[web.1]: 
2022-05-12T09:09:22.881337+00:00 app[web.1]: node:events:505
2022-05-12T09:09:22.881338+00:00 app[web.1]: throw er; // Unhandled 'error' event
2022-05-12T09:09:22.881338+00:00 app[web.1]: ^
2022-05-12T09:09:22.883241+00:00 app[web.1]: AbortError: The user aborted a request.
2022-05-12T09:09:22.883244+00:00 app[web.1]: at abort (/app/node_modules/node-fetch/lib/index.js:1448:16)
2022-05-12T09:09:22.883245+00:00 app[web.1]: at AbortSignal.abortAndFinalize (/app/node_modules/node-fetch/lib/index.js:1463:4)
2022-05-12T09:09:22.883246+00:00 app[web.1]: at AbortSignal.dispatchEvent (/app/node_modules/event-target-shim/dist/event-target-shim.js:818:35)
2022-05-12T09:09:22.883246+00:00 app[web.1]: at abortSignal (/app/node_modules/abort-controller/dist/abort-controller.js:52:12)
2022-05-12T09:09:22.883247+00:00 app[web.1]: at AbortController.abort (/app/node_modules/abort-controller/dist/abort-controller.js:91:9)
2022-05-12T09:09:22.883247+00:00 app[web.1]: at Timeout._onTimeout (/app/index.js:12:16)
2022-05-12T09:09:22.883248+00:00 app[web.1]: at listOnTimeout (node:internal/timers:559:17)
2022-05-12T09:09:22.883248+00:00 app[web.1]: at processTimers (node:internal/timers:502:7)
2022-05-12T09:09:22.883249+00:00 app[web.1]: Emitted 'error' event on PassThrough instance at:
2022-05-12T09:09:22.883249+00:00 app[web.1]: at emitErrorNT (node:internal/streams/destroy:157:8)
2022-05-12T09:09:22.883249+00:00 app[web.1]: at emitErrorCloseNT (node:internal/streams/destroy:122:3)
2022-05-12T09:09:22.883250+00:00 app[web.1]: at processTicksAndRejections (node:internal/process/task_queues:83:21) {
2022-05-12T09:09:22.883251+00:00 app[web.1]: type: 'aborted'
2022-05-12T09:09:22.883251+00:00 app[web.1]: }
2022-05-12T09:09:23.020958+00:00 heroku[web.1]: Process exited with status 1
2022-05-12T09:09:23.059270+00:00 heroku[web.1]: State changed from up to crashed
```

**Comment by epicfaace** [comment]
Yay!
